amcl:
  ros__parameters:
    base_frame_id: "base_link"
    transform_tolerance: 5.0
    use_sim_time: false

map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: ""

map_saver:
  ros__parameters:
    use_sim_time: false
    save_map_timeout: 5.0
    free_thresh: 0.25
    occupied_thresh: 0.65
    map_subscribe_transient_local: true

planner_server:
  ros__parameters:
    expected_planner_frequency: 1.0
    use_sim_time: false
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_smac_planner::SmacPlanner2D"
      allow_unknown: true
      tolerance: 0.5
      tolerance: 0.5
      use_astar: true
      allow_unknown: true
      interpolation_resolution: 0.15
      path_downsample_ratio: 2

controller_server:
  ros__parameters:
    controller_frequency: 20.0
    use_sim_time: false
    publish_zero_velocity: true
    odom_topic: "odom"
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["goal_checker"]
    controller_plugins: ["FollowPath"]
    
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0
    
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 6.3
      stateful: false

    FollowPath:
      plugin: "nav2_rotation_shim_controller::RotationShimController"
      primary_controller: "dwb_core::DWBLocalPlanner"
      angular_dist_threshold: 0.3
      angular_disengage_threshold: 0.1
      forward_sampling_distance: 0.0
      rotate_to_heading_angular_vel: 1.2
      max_angular_accel: 2.0
      simulate_ahead_time: 1.0
      rotate_to_goal_heading: true
      closed_loop: true
      use_path_orientations: false
      debug_trajectory_details: false
      min_vel_x: -0.4
      min_vel_y: 0.0
      max_vel_x: 0.0
      max_vel_y: 0.0
      max_vel_theta: 0.5
      min_vel_theta: -0.5
      min_speed_xy: 0.05
      max_speed_xy: 1.0
      min_speed_theta: 0.0
      acc_lim_x: 0.75
      acc_lim_y: 0.0
      acc_lim_theta: 2.0
      decel_lim_x: -2.0
      decel_lim_y: 0.0
      decel_lim_theta: -3.2
      vx_samples: 20
      vy_samples: 5
      vtheta_samples: 40
      sim_time: 2.5
      linear_granularity: 0.05
      angular_granularity: 0.025
      transform_tolerance: 1.0
      xy_goal_tolerance: 0.1
      trans_stopped_velocity: 0.05
      short_circuit_trajectory_evaluation: true
      stateful: false
      critics: ["Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]

    Oscillation:
      scale: 1.0

    BaseObstacle:
      scale: 0.015

    PathAlign:
      scale: 8.0

    GoalAlign:
      scale: 8.0

    PathDist:
      scale: 24.0

    GoalDist:
      scale: 16.0


bt_navigator:
  ros__parameters:
    use_sim_time: false
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"

behavior_server:
  ros__parameters:
    use_sim_time: false
    behavior_plugins: ["spin", "backup", "wait"]
    spin:
      plugin: "nav2_behaviors::Spin"
      spin_dist: 3.14      # Full 180° turns
      time_allowance: 10.0
    backup:
      plugin: "nav2_behaviors::BackUp"
      backup_dist: -0.5    # Increased reverse distance
      backup_speed: -0.25  # Slower reverse for precision
      time_allowance: 10.0
    wait:
      plugin: "nav2_behaviors::Wait"

waypoint_follower:
  ros__parameters:
    use_sim_time: false
    loop_rate: 20
    stop_on_failure: false

local_costmap:
  local_costmap:
    ros__parameters:
      robot_base_frame: base_link
      transform_tolerance: 0.5
      width: 20
      height: 20
      origin_x: -6.0  # Move origin backward
      origin_y: -6.0
      footprint: "[[0.52, -0.52], [0.52, 0.52], [-0.52, 0.52], [-0.52, -0.52]]"
      use_sim_time: false
      always_send_full_costmap: true
      track_unknown_space: true
      update_frequency: 10.0
      publish_frequency: 5.0
      global_frame: odom
      robot_base_frame: base_link
      resolution: 0.1
      rolling_window: true
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: laser_scan_sensor
        laser_scan_sensor:
          topic: /scan
          sensor_frame: base_scan
          data_type: LaserScan
          clearing: true
          marking: true
          min_obstacle_height: 0.0
          max_obstacle_height: 2.0
          obstacle_range: 6.0
          raytrace_range: 8.0
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.25
        cost_scaling_factor: 2.5

global_costmap:
  global_costmap:
    ros__parameters:
      robot_base_frame: base_link
      transform_tolerance: 0.5
      width: 20
      height: 20
      origin_x: -6.0  # Move origin backward
      origin_y: -6.0
      footprint: "[[0.52, -0.52], [0.52, 0.52], [-0.52, 0.52], [-0.52, -0.52]]"
      use_sim_time: false
      always_send_full_costmap: true
      track_unknown_space: true
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      resolution: 0.1
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        enabled: true
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: laser_scan_sensor
        laser_scan_sensor:
          topic: /scan
          sensor_frame: base_scan
          data_type: LaserScan
          clearing: true
          marking: true
          min_obstacle_height: 0.0
          max_obstacle_height: 2.0
          obstacle_range: 6.0
          raytrace_range: 8.0
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.25
        cost_scaling_factor: 2.5
